
services:
  mongodb:
    image: mongo:7
    container_name: mongo-serverless
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: ryan-serverless
    volumes:
      - mongodb_data:/data/db
volumes:
  mongodb_data: