# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: ryanpsouza
# "service" is the name of this project. This will also be added to your AWS resource names.
service: primeiro-serverless

plugins:
  - serverless-offline


params:
  default:
    dbName: ryan-serverless
  dev:
    connectionString: mongodb://root:root@localhost:27017/ryan-serverless?authSource=admin

provider:
  name: aws
  runtime: nodejs20.x
  environment:
    MONGODB_CONNECTIONSTRING: ${param:connectionString}
    MONGODB_DB_NAME: ${param:dbName}

functions:
  getTarefas:
    handler: handler.getTarefas
    timeout: 10
    events:
      - httpApi:
          path: /tarefas
          method: get

  postTarefas:
    handler: handler.postTarefas
    events:
      - http:
          path: /tarefas
          method: post
          request:
            schemas:
              application/json: ${file(./schemas/postTarefa.json)}

  
